### ISSUE TITLE
Creation of Interface for Handling Calls from Higher Providers

### ISSUE THREAD

**Issue by Lomet** [The-Poolz/LockDealNFT#12]
### Description:

There is a need to create a new interface that will manage the calls from "higher" providers. This interface will be utilized in the external creation. The external creation will handle the token transfers, while the `initiate` function will manage only the data structures.

### Proposed Changes:

1. **Interface Creation:** 
    - Create an interface to manage calls from "higher" providers. This interface will streamline communication and enhance interactivity between different provider levels.

2. **External Creation Update:**
    - External creation should manage token transfers. This shift in responsibility will enhance the consistency of token transfers.

3. **`Initiate` Function Update:**
    - The `initiate` function should focus on managing only the data structures. This specification of responsibility will improve the accuracy and efficiency of data handling.

4. **Approved Providers List:**
    - Add a list of approved providers that can call the interface. This list will act as a control measure to ensure only authorized providers can interact with the interface.

### Expected Outcome:

With these changes, we aim to segregate responsibilities more effectively among different components of the system. Token transfers will be handled by external creation, data structures will be managed by the `initiate` function, and interactions with the interface will be controlled via an approved providers list. This setup will provide better control over different operations and improve the overall efficiency of the system.

**Comment by YouStillAlive** [comment]
closed by #29, #44
