### ISSUE TITLE
Fixed the dataPoolId issue on split function

### ISSUE THREAD

**Issue by 0xSolcroot** [The-Poolz/LockDealNFT#133]
In case of the bundleProvider split, the wrong `dataPoolId` is set.
`dataPoolId = poolId - 2` is wrong. It should be `dataPoolId = poolId`
https://github.com/The-Poolz/LockDealNFT/blob/6b6172f432e9d45c44e3e852409caa6684acb24b/contracts/LockDealNFT/LockDealNFT.sol#L97-L105

**Comment by YouStillAlive** [comment]
closed in #158
