### ISSUE TITLE
crezy idea

### ISSUE THREAD

**Issue by Lomet** [The-Poolz/LockDealNFT#199]
https://github.com/The-Poolz/LockDealNFT/blob/3a2633489a82b3bb7df5fea74e878921ed464e12/contracts/AdvancedProviders/BundleProvider/BundleProvider.sol#L122

make this line
` for (++poolId; poolId <= lastSubPoolId; ++poolId) {`

**Comment by YouStillAlive** [comment]
With **Bundle** comprising 3 providers, updating `split`, `withdraw`, and `getTotalRemainingAmount` brings a minor gas reduction of about `70-140`. Nevertheless, as the number of providers increases, gas savings will amplify accordingly.
