### ISSUE TITLE
Refactor `split` function in `TimedLockDealProvider` contract

### ISSUE THREAD

**Issue by Lomet** [The-Poolz/LockDealNFT#22]
**Problem Statement:**
The `split` function in `TimedLockDealProvider` currently performs both calculations and state changes, making it hard to read and maintain. We need to improve the modularity of this function.

**Proposed Solution:**
Refactor the `split` function by extracting the calculation logic into an internal function. This will make the function easier to understand and modify. It will also allow us to implement the layered calling pattern discussed in other issues, where higher-level providers call base-level providers.

**Detailed Design:**
1. Extract the calculation logic from the `split` function into an internal function named `_calculateSplit`. This function should take the same arguments as the `split` function and return all the values that need to be calculated.

2. Refactor the `split` function to first call `_calculateSplit`, then perform the state changes and emit the event.

3. Implement the layered calling pattern by making `TimedLockDealProvider` call `BaseLockDealProvider`, which will then call `DealProvider`. This will be done in the `split` function after the state changes.

**Acceptance Criteria:**
- The `split` function is refactored according to the design described above.
- All tests pass after the refactoring.

**Comment by YouStillAlive** [comment]
closed by #33
