### ISSUE TITLE
Implement DealProvider in LockDealNFT

### ISSUE THREAD

**Issue by Lomet** [The-Poolz/LockDealNFT#24]
### Description

In order to add an extra layer of security and simplify the interaction with the LockDealNFT contract, we should implement the DealProvider functionality directly within the LockDealNFT contract. This will allow users to interact with a single contract (LockDealNFT) while ensuring that the appropriate functions are called within the corresponding providers.

### Tasks

1. Modify the LockDealNFT contract to include the DealProvider interface and functions.
2. Implement the necessary logic in LockDealNFT to forward the function calls to the respective providers.
3. Add modifiers to the provider contracts to allow only the base NFT contract to call the functions.
4. Update the existing providers (BaseLockDealProvider and TimedLockDealProvider) to include the modifier restricting access to only the base NFT contract.
5. Update the documentation and tests to reflect the changes.

### Acceptance Criteria

- The LockDealNFT contract includes the DealProvider interface and functions.
- The LockDealNFT contract correctly forwards function calls to the respective providers based on the function being called.
- Modifiers are added to the provider contracts to restrict access to only the base NFT contract.
- Documentation and tests are updated to reflect the changes.

**Comment by YouStillAlive** [comment]
closed by #29, #41, #47
