### ISSUE TITLE
try optimizing `getWithdrawableAmount` in `TimedDealProvider`

### ISSUE THREAD

**Issue by YouStillAlive** [The-Poolz/LockDealNFT#285]

**Comment by YouStillAlive** [comment]
```solidity
    // gas cost: 22482
    function getWithdrawableAmount(uint256 poolId) public view override returns (uint256) {
        uint256[] memory params = getParams(poolId);
        uint256 leftAmount = params[0];
        uint256 startTime = params[1];
        uint256 finishTime = params[2];
        uint256 startAmount = params[3];

        if (block.timestamp < startTime) return 0;
        if (finishTime <= block.timestamp) return leftAmount;

        uint256 totalPoolDuration = finishTime - startTime;
        uint256 timePassed = block.timestamp - startTime;
        uint256 debitableAmount = (startAmount * timePassed) / totalPoolDuration;
        return debitableAmount - (startAmount - leftAmount);
    }
```
In our case, the use of variables reduces gas costs. `176 fewer gases` than when using params index elements. 
```solidity
    // gas cost: 22658
    function getWithdrawableAmount(uint256 poolId) public view override returns (uint256) {
        uint256[] memory params = getParams(poolId);

        if (block.timestamp < params[1]) return 0;
        if (params[2] <= block.timestamp) return params[0];

        uint256 totalPoolDuration = params[2] - params[1];
        uint256 timePassed = block.timestamp - params[1];
        uint256 debitableAmount = (params[3] * timePassed) / totalPoolDuration;
        return debitableAmount - (params[3] - params[0]);
    }
```

**Comment by Lomet** [comment]
Do you want to close it or make another try?

> ```solidity
>     // gas cost: 22482
>     function getWithdrawableAmount(uint256 poolId) public view override returns (uint256) {
>         uint256[] memory params = getParams(poolId);
>         uint256 leftAmount = params[0];
>         uint256 startTime = params[1];
>         uint256 finishTime = params[2];
>         uint256 startAmount = params[3];
> 
>         if (block.timestamp < startTime) return 0;
>         if (finishTime <= block.timestamp) return leftAmount;
> 
>         uint256 totalPoolDuration = finishTime - startTime;
>         uint256 timePassed = block.timestamp - startTime;
>         uint256 debitableAmount = (startAmount * timePassed) / totalPoolDuration;
>         return debitableAmount - (startAmount - leftAmount);
>     }
> ```
> 
> In our case, the use of variables reduces gas costs. `176 fewer gases` than when using params index elements.
> 
> ```solidity
>     // gas cost: 22658
>     function getWithdrawableAmount(uint256 poolId) public view override returns (uint256) {
>         uint256[] memory params = getParams(poolId);
> 
>         if (block.timestamp < params[1]) return 0;
>         if (params[2] <= block.timestamp) return params[0];
> 
>         uint256 totalPoolDuration = params[2] - params[1];
>         uint256 timePassed = block.timestamp - params[1];
>         uint256 debitableAmount = (params[3] * timePassed) / totalPoolDuration;
>         return debitableAmount - (params[3] - params[0]);
>     }
> ```
