### ISSUE TITLE
add IERC165 checker for `_createNewSubPool` in `BundleProvider`

### ISSUE THREAD

**Issue by YouStillAlive** [The-Poolz/LockDealNFT#286]

**Comment by Lomet** [comment]
> We have a hash check of `Bundable._INTERFACE_ID_BUNDABLE` for providers.
> 
> https://github.com/The-Poolz/LockDealNFT/blob/4fb4591c41bcca3d7bcbb2fdcecd30ffcbe6a6b3/contracts/AdvancedProviders/BundleProvider/BundleModifiers.sol#L27

then we can remove the other checks?
