### ISSUE TITLE
`RefundProvider` `getParams` bug

### ISSUE THREAD

**Issue by YouStillAlive** [The-Poolz/LockDealNFT#295]
Calling `getParams` with a non-existing pool ID will fail. `lockDealNFT.poolIdToProvider(poolId + 1)` will return address zero. Then we call `getParams` from address zero.
https://github.com/The-Poolz/LockDealNFT/blob/4aa80c0b4ded05c8718a3e434ad1b09cf1d50cbb/contracts/AdvancedProviders/RefundProvider/RefundState.sol#L11-L13

**Comment by Lomet** [comment]
`address(lockDealNFT.poolIdToProvider(poolId)) == this`
