### ISSUE TITLE
`RefundProvider` withdraw

### ISSUE THREAD

**Issue by YouStillAlive** [The-Poolz/LockDealNFT#299]
In the current implementation, `RefundProvider` can't use `BundleProvider` as `dataPoolID` for withdrawals. `BundleProvider` doesn't have `ISimpleProvider` interface.
https://github.com/The-Poolz/LockDealNFT/blob/6877d78da7d62af1d81ac41b845c89d492e608a6/contracts/AdvancedProviders/RefundProvider/RefundProvider.sol#L126-L130

Possible solutions:
* all `withdraw(uint256)` will have the `onlyProvider` modifier instead of `onlyNFT`.
* `BundleProvider` will implement `ISimpleProvider` (we can rename it).

**Comment by Lomet** [comment]
we can add another ERC165 check here, or make a better function for all providers on withdraw
