### ISSUE TITLE
Add the owner and token addresses check on createNewPool() function

### ISSUE THREAD

**Issue by 0xSolcroot** [The-Poolz/LockDealNFT#79]
Check if the owner and token addresses are not address(0) on createNewPool() function of each provider.

**Comment by YouStillAlive** [comment]
Each `createNewPool` function calls `mint`. `mint` already has `notZeroAddress` and `notZeroAmount` modifiers.
https://github.com/The-Poolz/LockDealNFT/blob/f8d9dbf31a972e27c27a829241df49977684a105/contracts/LockDealNFT/LockDealNFT.sol#L28-L30
