### ISSUE TITLE
add indexed keyword to BasePoolInfo in NewPoolCreated event

### ISSUE THREAD

**Issue by YouStillAlive** [The-Poolz/LockDealNFT#83]
add **indexed** keyword to `BasePoolInfo` in `NewPoolCreated` event.
https://github.com/The-Poolz/LockDealNFT/blob/a2ec0d7ceeeb5dcc75ed6661c23dd20e339b69e0/contracts/DealProvider/IDealProvierEvents.sol#L18

**Comment by 0xSolcroot** [comment]
@YouStillAlive do you mean this one?
`event NewPoolCreated(BasePoolInfo indexed poolInfo, uint256[] params); `

**Comment by 0xSolcroot** [comment]
Update the event like this.
`event NewPoolCreated(uint256 indexed poolId, address indexed owner, address indexed token, uint256[] params);`
