### ISSUE TITLE
add getData to LockedDealNFT contract

### ISSUE THREAD

**Issue by YouStillAlive** [The-Poolz/LockDealNFT#87]
Need to add a `getData` function to **LockedDealNFT** contract. The function calls the getData function from the **Provider** depending on the pool id.  This will deprive us of the possibility of not choosing the correct **provider** when returning data in case of a mismatch between the pool id and the providers.
```solidity
    function getData(uint256 poolId)
        external
        view
        returns (IDealProvierEvents.BasePoolInfo memory poolInfo, uint256[] memory params)
    {
        if (_exists(poolId)) {
            return IProvider(poolIdToProvider[poolId]).getData(poolId);
        }
    }
```

**Comment by Lomet** [comment]
we can add a new function to each provider,
```
GetName
```
and return here the name of the provider in this function

**Comment by YouStillAlive** [comment]
if we need this information, we can also return the address of the provider, like:
```solidity
returns (address provider, IDealProvierEvents.BasePoolInfo memory poolInfo, uint256[] memory params)
```

**Comment by Lomet** [comment]
> ```solidity
> provider
> ```

yes, this is the idea, but then the front (application) needs to know each provider's address.
if we return some static string (name) - we can do an enum, and when contact replaces the new provider if the name is the same 
there is 0 change in front.
